spring.application.name=tienda
server.port=8081

#Clase 2 
#Define fecha y hora
logging.pattern.dateformat=hh:mm

#Elimina mensajes invasivos de Spring
spring.main.banner-mode=off

#En desarrollo el 'cache' del servidor (false), en produccion 'true'
spring.thymeleaf.cache=false